server.port=8081
server.address=0.0.0.0
spring.application.name=user-service

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:/data/userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security
security.jwt.secret=ChangeThisSecretInProd_32charsMinimum_1234567890
security.jwt.expiration-ms=3600000

# Application
app.frontend.base-url=http://localhost:3000
app.mail.from=noreply@tldr.local

app.mail.from=urbanlease01@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=urbanlease01@gmail.com
spring.mail.password=fbxl axjx gkau voke
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# External Services
services.comment.base-url=http://localhost:8084