version: "3.8"

services:
  user-service:
    build:
      context: ./backend/user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  summary-service:
    build:
      context: ./backend/summary-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  vote-service:
    build:
      context: ./backend/vote-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  comment-service:
    build:
      context: ./backend/comment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  saved-service:
    build:
      context: ./backend/saved-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  recommendation-service:
    build:
      context: ./backend/recommendation-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  circle-service:
    build:
      context: ./backend/circle-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    networks:
      - tldr-network
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - summary-service
      - vote-service
      - comment-service
      - saved-service
      - recommendation-service
      - circle-service
    networks:
      - tldr-network
    restart: always

networks:
  tldr-network:
    driver: bridge