[supervisord]
nodaemon=true
user=root

[program:user-service]
command=java -jar /app/backend/user-service/user-service-1.0.0.jar

[program:summary-service]
command=java -jar /app/backend/summary-service/summary-service-1.0.0.jar

[program:vote-service]
command=java -jar /app/backend/vote-service/vote-service-1.0.0.jar

[program:comment-service]
command=java -jar /app/backend/comment-service/comment-service-1.0.0.jar

[program:saved-service]
command=java -jar /app/backend/saved-service/saved-service-1.0.0.jar

[program:recommendation-service]
command=java -jar /app/backend/recommendation-service/recommendation-service-1.0.0.jar

[program:circle-service]
command=java -jar /app/backend/circle-service/circle-service-1.0.0.jar
