[supervisord]
nodaemon=true
user=root

[program:user-service]
command=java -jar /app/backend/user-service/target/user-service-1.0.0.jar

[program:summary-service]
command=java -jar /app/backend/summary-service/target/summary-service-1.0.0.jar

[program:vote-service]
command=java -jar /app/backend/vote-service/target/vote-service-1.0.0.jar

[program:comment-service]
command=java -jar /app/backend/comment-service/target/comment-service-1.0.0.jar

[program:saved-service]
command=java -jar /app/backend/saved-service/target/saved-service-1.0.0.jar

[program:recommendation-service]
command=java -jar /app/backend/recommendation-service/target/recommendation-service-1.0.0.jar

[program:circle-service]
command=java -jar /app/backend/circle-service/target/circle-service-1.0.0.jar

[program:frontend]
command=nginx -g "daemon off;"
